---
- hosts: localhost
  tasks:
    - name: Install python pip
      apt:
        name: python3-pip
        state: present
    - name: Install docker
      apt:
        name: docker
        state: present
    #- name: start docker
    #  service:
    #    name: docker
    #    state: started
    #    enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        version: 1.10.6
        state: present
    - name: Start the container
      docker_container:
        name: devopsmaven
        image: "312314205034/devopsmaven:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8061:8080
